Update scripts to work with nixos

diff --git a/.local/bin/eww/volume b/.local/bin/eww/volume
--- a/.local/bin/eww/volume
+++ b/.local/bin/eww/volume
@@ -1,41 +1,42 @@
 #!/bin/sh
-# Wrapper for pactl to update the volume widget of the eww status bar
+# Wrapper for pamixer to update the volume widget of the eww status bar
 # Script is minimal because it needs to be hella fast, so no argument chekcing
 # -c to change volume to "$2"
-# -g to get the current "$volume_label"
+# -g to get the current "$volume"
 # -m to mute
 
-set_volume_label()
+setVolume()
 {
-	volume_label="$(pactl get-sink-volume @DEFAULT_SINK@ | awk 'NR==1{print $5}' | tr -d '%')"
+	volume="$(pamixer --get-volume)"
 
-	if [ "$(pactl get-sink-mute @DEFAULT_SINK@)" = "Mute: yes" ]; then
-		volume_label="󰝟 $volume_label%"
-	elif [ "$volume_label" -eq 0 ]; then
-		volume_label=" $volume_label%"
-	elif [ "$volume_label" -lt 50 ]; then
-		volume_label=" $volume_label%"
+	if [ "$(pamixer --get-mute)" = "true" ]; then
+		volume="󰝟 $volume%"
+	elif [ "$volume" -eq 0 ]; then
+		volume=" $volume%"
+	elif [ "$volume" -lt 50 ]; then
+		volume=" $volume%"
 	else
-		volume_label=" $volume_label%"
+		volume=" $volume%"
 	fi
 }
 
-update_eww()
-{
-	set_volume_label
-	eww update volume-level="$volume_label"
-}
-
 case "$1" in
-	-c)
-		pactl set-sink-volume @DEFAULT_SINK@ "$2"
-		update_eww ;;
 	-g)
-		set_volume_label
-		echo "$volume_label" ;;
-	-m)
-		pactl set-sink-mute @DEFAULT_SINK@ toggle
-		update_eww ;;
+		setVolume
+		echo "$volume";;
+	-i)
+		pamixer -i "$2"
+		setVolume
+		eww update volume-level="$volume";;
+	-d)
+		pamixer -d "$2"
+		setVolume
+		eww update volume-level="$volume";;
+	-t)
+		pamixer --toggle-mute
+		setVolume
+		eww update volume-level="$volume";;
 	*)
-		echo "Option error $1" >&2;;
+		echo "Option error $1" >&2
+		echo "Usage -c to change volume in %, -g to get volume, -m to mute";;
 esac
